name: Download and Process CRAN Logs (Last 30 Days)

on:
  push:
    branches: [master, main]
  schedule:
    - cron: '0 23 * * 0'

jobs:
  process_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Download CRAN logs for last 30 days
        run: |
          current_date=$(date +'%Y-%m-%d')
          current_year=$(date +'%Y')
          echo "Current date: $current_date, Year: $current_year"
          for i in {0..4}; do
            day=$(date -d "$current_date -$i day" +'%Y-%m-%d')
            url="http://cran-logs.rstudio.com/${current_year}/${day}.csv.gz"
            echo "Downloading ${url} ..."
            curl -s -f -O "${url}" || echo "WARNING: ${url} not found."
          done

      - name: Decompress each log file
        run: |
          for file in *.csv.gz; do
            [ -e "$file" ] || continue
            day=$(basename "$file" .csv.gz)
            echo "Decompressing $file to ${day}.csv ..."
            gunzip -c "$file" > "${day}.csv"
          done

      - name: Removed compressed files
        run: |
          rm *.gz

      - name: Aggregate counts by package using R
        run: |
          nix-shell -p R rPackages.data_table --run 'Rscript -e "library(data.table);
            files <- list.files(pattern=\"\\\d.*csv\");
            if(length(files)==0) stop(\"No CSV files found\");
            result <- vector(mode = "list", length = length(files));
            for(i in seq_along(files)) {
              dt <- fread(files[i]);
              result[[i]] <- dt[, .N, by = package];
            };
            dt <- rbindlist(result);
            agg <- dt[, .N, by = package][order(-N)];
            fwrite(agg, \"aggregated_counts.csv\")"'

      - name: Commit and push aggregated_counts.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [ -n "$(git status --porcelain aggregated_counts.csv)" ]; then
            git add aggregated_counts.csv
            git commit -m "Update aggregate counts for CRAN logs"
            git push
          else
            echo "No changes to commit."
          fi
